services:
  lamport-server:
    build:
      context: ../
      dockerfile: Sync/Dockerfile
    container_name: lamport-server
    working_dir: /app/Sync
    command: ["python", "s_lamp.py"]
    volumes:
      - ../Sync:/app/Sync:rw
  lamport-client:
    build:
      context: ../
      dockerfile: Sync/Dockerfile
    container_name: lamport-client
    depends_on:
      - lamport-server
    working_dir: /app/Sync
    command: ["python", "c_lamp.py"]
    volumes:
      - ../Sync:/app/Sync:rw